server:
  port: 0

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      # h2 DB에 대해서 외부 접속 허용
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    # 통신할 Eureka Server의 위치를 지정하고 Eureka Server에 이 Eureka Client를 등록
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  # Spring Boot가 제공하는 랜덤포트 0 대신에 인스턴스 이름 규칙을 지정
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

greeting:
  message: Welcome to the Simple E-commerce.

logging:
  level:
    com.example.userservice: DEBUG

token:
  expiration_time: 86400000
  secret: usertokenusertokenusertokenusertokenusertokenusertoken
